### PR TITLE
Private events

### PR DESCRIPTION
**Pull request by prolajumokeoni**
In this project, created an app where:
- Added authentication through devise
-  users can create events
-  users can also register for events created by other users

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: :construction_worker_woman: 

@prolajumokeoni , this is a really decent effort. :clap: Good job.

**Highlight**

- [x] Your repo looks professional, not informing of any linters error as well as the correct gitflow.
- [ ] Extra credit for the extra feature you implemented by adding the file attachment functionality. This would proof very useful for your capstone project.

Good job. :clap: :+1: 

**To Improve**
Below are the required changes that needs to be implemented to get this project approved.
**App Behaviour**
- [x] Event's index page should display past and upcoming events lists. Currently, all created events on the index page are lumped together irrespective of whether past or upcoming.
- [x] The user's show page should display events the user has created and events that the user is attending to be separated in past and upcoming. Currently, there's no user show page. Please create a show page for users.
- [x] Currently, a logged in user is able to register for multiple events. Please fix this. 

**Models**

- [x] Event model should have scope for upcoming events. i.e `scope :upcoming, -> { where('date >= ?', Time.zone.now) }`
- [x] Event model should have scope for previous events. i.e `scope :previous, -> { where('date < ?',  Time.zone.now) }`

**Associations**

- [ ] User model: `has_many :events, foreign_key: :creator_id.`
- [ ] Event model: `belongs_to :creator, class_name: "User"` . This means that Events table has creator_id(still a user) as the foreign key.
- [ ] Since you're using a through table (Register), you should add this: `User model has_many :attended_events, through: :registers` NB: attended_events could be anything naming you choose. Also, Event model ` has_many :attendees, through: :registers`

**Controllers**
Events
- [ ] Create action should use the #build association reference method, i.e. `current_user.events.build(event_params)` to create the new event with the user’s ID pre-populated. No use of the Event’s `::new` method to manually enter the ID.
- [ ] Index action should list past events, i.e. `@past_events = Event.previous_events`.
- [ ] Index action should list upcoming events, i.e.` @upcoming_events = Event.upcoming_events`

Users
You currently have no user controller. Your user controller should include the following:

- [ ] Show action should list events created by user, i.e. `@created_events = current_user.events`.
- [ ] Show action should list events previously attended by user using event model scope, i.e. `@past_events = current_user.attended_events.previous`
- [ ] Show action should list upcoming events previously attended by user using event model scope, i.e. `@upcoming_events = current_user.attended_events.upcoming `

**Tests**

- [ ] Models should have unit tests for validations and associations (Rspec).
- [ ] Authentication should have integration tests (Rspec + Capybara).
- [ ] Event management features should have integration tests (Rspec + Capybara).

[OPTIONAL]

- [ ] Please remove all logic from your view files. You can make use of helper methods to handle that.

Please, don't be overwhelmed. Consider this as an opportunity to improve your project and to learn.

If you require support or need clarification, please drop your message here and ping me on slack (george gbenle)

Make the required changes and submit another CRR when you're ready. 

Cheers :smile:  With much respect. :tophat:

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUIRED** :recycle: :recycle: :construction_worker_woman: 

It's really impressive that you've implemented almost all the changes from the last review. Good job :+1: 

**Highlights** among others:
:heavy_check_mark:  Event's index page now displays past and upcoming events lists.
:heavy_check_mark: The user's show page now display events the user has created and events that the user is attending.
:heavy_check_mark: You have added scope to your events for past and upcoming.
:heavy_check_mark: You have added some tests.

These and many more. I congratulate you. :clap: 

**To improve:**
Kindly see below lists of changes half implemented or yet to be implemented.

- [x] There is a user show page but there's no how to navigate to the page with a click. I had to manually edit the url to see the user show page. You could make a click on the username lead to the user show page. Currently, it leads to the edit user page.
- [ ] As a logged in user, I can still register myself to attend an event many times. Please fix it.
- [ ] Please test your associations. That is essentially what this project is all about - Associations. Also add integration tests.

**That's it.**

Please make these changes and submit another CRR when you're ready.
Drop your message here and ping me on slack if you require clarification or support.

Cheers :smile: With respect. :tophat:

**Review by george-shammar — APPROVED** [review]
### **STATUS: APPROVED** :heavy_check_mark: :heavy_check_mark: 

@prolajumokeoni , Good job with the implemented changes.

**Highlights**
:heavy_check_mark: You've added more tests and they're all passing.
:heavy_check_mark: You've fixed the link to the user show page.
Well done :+1: 

I'm happy to approve this project.

I wish you good luck.

**Cheers** :smile: **With respect.** :tophat:

**Comment by prolajumokeoni** [comment]
Thankyou @george-shammar

**Pull request closed without merging**
